#!/bin/bash
echo [Desktop Entry]
echo # 
echo Encoding=UTF-8
echo Name=$USER/bin/xmonad.start as xsession w/gnome fallback
echo Comment=use your xmonad.start as an xsession, fallback to gnome-session
echo Exec=$HOME/bin/xmonad.start
echo TryExec=gnome-session
echo Icon=xmonad.png
echo Type=Application

#####
# EOF
