#!/bin/bash
echo [Desktop Entry]
echo # 
echo Encoding=UTF-8
echo Name=xmonad-$USER
echo Comment=Leightweight tiling window manager
echo Exec=$HOME/bin/xmonad.start
echo Icon=xmonad.png
echo Type=XSession

#####
# EOF
